### ISSUE TITLE
Please mention archiso as a requirement

### ISSUE THREAD

**Issue by ghost** [virtapi/LARS#21]
After cloning the repository and rebuild_and_copy.sh, the script immediately failed because I didn't have the "archiso" package installed. It was easy to figure out which package was needed but isn't currently mentioned at least in the README.md file. Please extend the documentation to cover this and possibly other required packages that are not mentioned yet.

**Comment by bastelfreak** [comment]
this was fixed in https://github.com/virtapi/LARS/commit/6d8716c31f00057be4f2621957fea0a4989ed303
