### ISSUE TITLE
[Question] Minimum system specs/ out of memory error / kernel panic

### ISSUE THREAD

**Issue by NickyHeuperman** [virtapi/LARS#47]
I've got an issue/question,

I've been succesfull in building the images and booting from it, I've noticed I need about 1.1GB of ram to succesfully boot over http, arch linux pxe install recommend loop booting over nfs on low memory issues (I'd like to run this on vms with a minimum of 512MB ram). Doing so however won't fully boot the image. It hangs on mounting the nfs shares, something that works fine with the http boot for whatever reason.

My current workflow is to pxe boot as the example given but I was wondering if there is any way I could make this boot over pxe without needing this much ram?

**Comment by bastelfreak** [comment]
Hi @NickyHeuperman, thanks for rising this issue! My images work fine with around 768mb of memory in a virtual machine. Could you show the packages.both/packages.x86_64? I guess you installed a long list of packages and the generated image is pretty huge?

**Comment by NickyHeuperman** [comment]
> arch-install-scripts
b43-fwcutter
btrfs-progs
clonezilla
crda
darkhttpd
ddrescue
dhclient
dialog
dmraid
dnsmasq
dnsutils
dosfstools
elinks
ethtool
f2fs-tools
fsarchiver
gnu-netcat
gpm
gptfdisk
grub
hdparm
ipw2100-fw
ipw2200-fw
lftp
linux-atm
mc
mtools
nfs-utils
nilfs-utils
nmap
ntfs-3g
ntp
openssh
partclone
parted
partimage
refind-efi
rsync
smartmontools
sudo
tcpdump
testdisk
usb_modeswitch
vim-minimal
wget
pkgfile
htop
lsof
strace
ruby
iperf3
bash-completion
moreutils
dfc
mdadm
ccze
screen
sysstat
ipmitool
intel-ucode
python-requests
python-pyudev
python-six
python-lxml
lshw
dmidecode

> 
Just the default packages I think, my current working theory is that ipxe takes up too much ram by comparison. Any idea why nfs loop booting doesn't exactly work? It's hard to debug when it won't even drop me to a console. I guess a workaround could be booting the iso directly or temporarily increasing ram during setup but any insight in the matter would be greatly appreciated. Thank you for your quick reaction. BTW the resulting image is about 566MB give or take

**Comment by bastelfreak** [comment]
566MB sound okay. In the worst case the system needs twice the size of the sqashfs as ramsize. It gets copied into the ram and afterwards extracted. The ram gets freed, but for a short amount of time it is normal that some memory is allocated. Can you share your ipxe/pxelinux config and NFS share options? maybe there is something we can optimize.

**Comment by bastelfreak** [comment]
ups wrong button

**Comment by NickyHeuperman** [comment]
No worries, shall do as soon as I get access to my setup again, won't be today though, thanks in advanceOn 13 Sep 2017 22:44, Tim Meusel <notifications@github.com> wrote:ups wrong button

**Comment by NickyHeuperman** [comment]
/etc/exports
`/export       10.10.0.0/24(ro,fsid=0,insecure,no_subtree_check,async)
/export/nfs 10.10.0.0/24(ro,nohide,insecure,no_subtree_check,async)
/export/archrescue 10.10.0.0/24(ro,no_subtree_check)`

Where nfs contains installimage and images and archrescue contains the unpacked iso, this is bound to the same folder as /var/www/archrescue
pxelinux.cfg

`DEFAULT archrescue_nfs
LABEL archrescue_http
  MENU LABEL Arch Linux Live Rescue (HTTP)
  LINUX http://10.10.0.204/archrescue/arch/boot/x86_64/vmlinuz
  INITRD http://10.10.0.204/archrescue/arch/boot/x86_64/intel_ucode.img
  INITRD http://10.10.0.204/archrescue/arch/boot/x86_64/archiso.img
  APPEND archiso_http_srv=http://10.10.0.204/archrescue/ archisobasedir=arch checksum=y nomodeset systemd.mask=systemd-machine-id-commit systemd.mask=systemd-tmpfiles-setup systemd.mask=ldconfig selinux=0 console=tty0 console=ttyS0,115200 script=/usr/local/bin/start_installimage
  SYSAPPEND 3`

`LABEL archrescue_nfs
  MENU LABEL Arch Linux Live Rescue (NFS)
  LINUX http://10.10.0.204/archrescue/arch/boot/x86_64/vmlinuz
  INITRD http://10.10.0.204/archrescue/arch/boot/x86_64/intel_ucode.img
  INITRD http://10.10.0.204/archrescue/arch/boot/x86_64/archiso.img
  APPEND archiso_nfs_srv=10.10.0.204:/export/archrescue archisobasedir=arch checksum=y nomodeset systemd.mask=systemd-machine-id-commit systemd.mask=systemd-tmpfiles-setup systemd.mask=ldconfig selinux=0 console=tty0 console=ttyS0,115200 copytoram=n script=/usr/local/bin/start_installimage ip=:::::eth0:dhcp
  SYSAPPEND 3`

As far as I can tell by the documentation of ArchLinux and pxelinux there should be no real difference between the two configs

**Comment by NickyHeuperman** [comment]
I have btw tried different ip= parameters, including ip=:::::*:dhcp and ip=:::::ens18:dhcp, archlinux seems to boot, tell me target network is reachable but then hangs on mounting /root/.installimage and /root/images

**Comment by NickyHeuperman** [comment]
In customize_airootfs.sh

`# add installimage NFS mounts
if [ -n "$ISO_NFSSERVER" ]; then
  echo "${ISO_NFSSERVER}:/export/nfs/install /root/.installimage nfs ro 0 0" >> /etc/fstab
  echo "${ISO_NFSSERVER}:/export/nfs/images /root/images nfs ro 0 0" >> /etc/fstab
  mkdir -p /root/{images,.installimage}
fi`

**Comment by NickyHeuperman** [comment]
For the past weekend I've been working on doing a port of LARS to alpine (Knowing alpine uses very little resources and can be quite small on disk) I have succeeded in getting that version of lars working on under 200MB ram. For now I'll close this issue as I'm no longer looking into Arch Linux
