### ISSUE TITLE
support automatic installimage

### ISSUE THREAD

**Issue by bastelfreak** [virtapi/LARS#8]
We need a script that is embedded into the ISO and:
- checks if a config is available at `$proto://$ip/$dir/$clientip/config.cfg`
- downloads this to `/root/.installimage/configs` if available!
- starts installimage: `/root/.installimage/installimage.in_screen -c config.cfg -a`

installimage should now run by itself and [reboot](https://github.com/virtapi/installimage/blob/master/installimage.in_screen#L43) at the end

the variables needs to be added to our [config.sh.example](https://github.com/virtapi/LARS/blob/master/config.sh.example)

the script will be called via our [script=... kernel cmdline](https://github.com/virtapi/LARS/blob/master/airootfs/root/.automated_script.sh) feature. fetching the script via http or directly calling the local version has to work.

**Comment by bastelfreak** [comment]
this is just a draft based on opinions from the IRC channel, we should discuss this further before somebody builds it

**Comment by bastelfreak** [comment]
the config will have json encoding, we need to transform the data into the [installimage format](https://github.com/virtapi/installimage/blob/master/configs/simple-debian64-raid-lvm). Use heavily use python and bash in the virtapi namespace should we should stay by these languages. Parsing json in bash sucks so we should use python here.

**Comment by rmartinjak** [comment]
For accessing a flat dictionary (i.e. a string->string map) stored in json from bash, something like https://gist.github.com/rmartinjak/3683b83ff202c5f4f4e2
should be sufficient.

**Comment by bastelfreak** [comment]
so it should be possible to loop through the array, and dynamically export the keys and the values into an installimage configfile. Are you interested in doing this @rmartinjak?

**Comment by bastelfreak** [comment]
I thought about this again, the script needs to parse parse the config and start the installimage. We've got  our config.sh to set variables in bash scripts, I don't want another config file for LARS. We could split up this PR into one script that downloads the config and starts the installimage and another that parses the downloaded config, this can be python, the first one should be bash.

**Comment by bastelfreak** [comment]
We should work with $mac and not $ip in the URL, we can enforce unique mac addresses, but if there are private subnets it is possible that two servers have the same ip address.

**Comment by bastelfreak** [comment]
The download script is partly implemented in https://github.com/virtapi/LARS/blob/feature-installimage-json/scripts/start_installimage#L29

**Comment by bastelfreak** [comment]
installimage can successful download the config file and parse it. the API has changed, we should migrate to v1/installimage/<mac>/config

**Comment by bastelfreak** [comment]
this got implemented
